export default {
  CREATE_CODING_TASK: "CREATE_CODING_TASK",
  UPDATE_CODING_TASK: "UPDATE_CODING_TASK",
  DELETE_CODING_TASK: "DELETE_CODING_TASK",
  SET_SUCCESS_SCORE: "SET_SUCCESS_SCORE",
  INSERT_TASK_TO: "INSERT_TASK_TO",
  UPDATE_TASK_OF: "UPDATE_TASK_OF",
  DELETE_TASK_FROM: "DELETE_TASK_FROM"
};
